# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NestedJSONRealm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'RealmSwift'
  # Pods for NestedJSONRealm

  target 'NestedJSONRealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NestedJSONRealmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
